version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: pyhello
    build: .
    #   context: .
    #   dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # volumes:
      #- ".:/app/"
      #- "E:\\pr\\docker.test:/app/"
    ports:
      - "80:80"
    networks:
      - webnet

 #visualizer:
 #  image: dockersamples/visualizer:stable
 #  ports:
 #    - "8080:8080"
 #  volumes:
 #    - "/var/run/docker.sock:/var/run/docker.sock"
 #  deploy:
 #    placement:
 #      constraints: [node.role == manager]
 #  networks:
 #    - webnet
 #
  fuckingredis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
    # volumes:
    #   - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      webnet:
        aliases:
          - fuckingredis_blahblash

networks:
  webnet: